version: '3.7'
services:
  web:
    build: .
  #  command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/blog
      - static_volume:/blog/mysite/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/var/www/mysite/staticfiles
    restart: always

volumes:
  postgres_data:
  static_volume:
